// <auto-generated />
using EPA.DB.MSSQL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EPA.DB.Migrations
{
    [DbContext(typeof(EpaContext))]
    [Migration("20171024111438_ProfDirections2")]
    partial class ProfDirections2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.ProfDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DirectionId");

                    b.Property<int>("Id_direction");

                    b.Property<int>("Id_test");

                    b.Property<int>("MaxPoint");

                    b.Property<int>("MinPoint");

                    b.Property<int?>("TestDetailedInfoId");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.HasIndex("TestDetailedInfoId");

                    b.ToTable("ProfDirection");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Quiz.Answers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<int>("Point");

                    b.Property<int?>("QestionID");

                    b.HasKey("ID");

                    b.HasIndex("QestionID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Quiz.Questions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Question");

                    b.Property<int?>("TestListIDId");

                    b.HasKey("ID");

                    b.HasIndex("TestListIDId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DirectionId");

                    b.Property<int>("Id_direction");

                    b.Property<int>("Id_university");

                    b.Property<string>("Name");

                    b.Property<int?>("UniversityId");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.TestDetailedInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApproximatedTime");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("QuestionsCount");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("District");

                    b.Property<string>("Name");

                    b.Property<string>("Site");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.ProfDirection", b =>
                {
                    b.HasOne("EPA.DB.MSSQL.Models.Direction", "Direction")
                        .WithMany("ProfDirections")
                        .HasForeignKey("DirectionId");

                    b.HasOne("EPA.DB.MSSQL.Models.TestDetailedInfo", "TestDetailedInfo")
                        .WithMany()
                        .HasForeignKey("TestDetailedInfoId");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Quiz.Answers", b =>
                {
                    b.HasOne("EPA.DB.MSSQL.Models.Quiz.Questions", "Qestion")
                        .WithMany("Answer")
                        .HasForeignKey("QestionID");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Quiz.Questions", b =>
                {
                    b.HasOne("EPA.DB.MSSQL.Models.TestDetailedInfo", "TestListID")
                        .WithMany()
                        .HasForeignKey("TestListIDId");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Specialty", b =>
                {
                    b.HasOne("EPA.DB.MSSQL.Models.Direction", "Direction")
                        .WithMany("Specialties")
                        .HasForeignKey("DirectionId");

                    b.HasOne("EPA.DB.MSSQL.Models.University", "University")
                        .WithMany("Specialties")
                        .HasForeignKey("UniversityId");
                });
#pragma warning restore 612, 618
        }
    }
}
