// <auto-generated />
using EPA.DB.MSSQL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EPA.DB.Migrations
{
    [DbContext(typeof(EpaContext))]
    partial class EpaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Date", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateValue");

                    b.HasKey("Id");

                    b.ToTable("Dates");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Quiz.Answers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<int>("Point");

                    b.Property<int?>("QestionID");

                    b.HasKey("ID");

                    b.HasIndex("QestionID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Quiz.Questions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Question");

                    b.Property<int?>("TestListIDId");

                    b.HasKey("ID");

                    b.HasIndex("TestListIDId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.TestDetailedInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApproximatedTime");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("QuestionsCount");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Quiz.Answers", b =>
                {
                    b.HasOne("EPA.DB.MSSQL.Models.Quiz.Questions", "Qestion")
                        .WithMany("Answer")
                        .HasForeignKey("QestionID");
                });

            modelBuilder.Entity("EPA.DB.MSSQL.Models.Quiz.Questions", b =>
                {
                    b.HasOne("EPA.DB.MSSQL.Models.TestDetailedInfo", "TestListID")
                        .WithMany()
                        .HasForeignKey("TestListIDId");
                });
#pragma warning restore 612, 618
        }
    }
}
